spring:
  cloud:
    stream:
      bindings:
        user:
          destination: user
          binder: rabbitmq
        address:
          destination: address
          binder: rabbitmq
        address-validation:
          destination: address.validation
          binder: rabbitmq
      binders:
        rabbitmq:
         type: rabbit
         environment:
           spring:
             rabbitmq:
               host: localhost
               port: 5672
               username: guest
               password: guest
               virtual-host: /